import React, {useState, useEffect} from "react";
import { useNavigate } from "react-router-dom";
import {  getSpecialItems } from '../repository/shopItems'; // Import shop items and functions
import organicFoodsImage from './organicFoodsImage.jpg'; 
import { Carousel, Card, Button } from "react-bootstrap";


function Home() {
  const [specialItems, setSpecialItems] = useState([]);
  
  const navigate = useNavigate();

  const navigateToShop = () => {
      navigate('/shop');
  };

  const navigateToSpecials = () => {
    navigate('/specials')
  }

  useEffect (()=>{
    const fetchData = async () => {
      try {
        const specials = await getSpecialItems();
        setSpecialItems(specials);
      } catch (error) {
        console.log("Error fetching special items:", error);
      }
    };
  
    fetchData();
  }, [] )

  return (
       <div>
      {/*Photo by <a href="https://unsplash.com/@marisolbenitez?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Marisol Benitez</a> on <a href="https://unsplash.com/photos/pile-of-vegetables-QvkAQTNj4zk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
      os/assorted-color-tomatoes-on-brown-wooden-surface-gwT4rs_xlUA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
      */}
      <div style={{
        backgroundImage: `url(${organicFoodsImage})`,
        backgroundSize: 'cover',
        padding: '220px 20px',
        textAlign: 'center',
        color: 'white',
        marginBottom: '2rem',
        borderRadius: '25px',
        overflow: 'hidden', 
        boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.2)'
        }}>

        <h1 style={{fontSize: '80px', color: '#5C832F', marginBottom: '1rem', fontFamily: 'Lato, sans-serif' }}>Welcome To SOIL</h1>
        <p className="lead" style={{ maxWidth: '600px', margin: 'auto' }}>Your home for organic and sustainable living.</p>
        <button
          onClick={navigateToShop}
          style={{
            marginTop: '2rem',
            padding: '10px 20px',
            fontSize: '1.2rem',
            color: 'white',
            backgroundColor: '#5C832F',
            border: 'none',
            borderRadius: '25px',
            cursor: 'pointer',
            transition: 'background-color 0.3s',
            boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.2)'
          }}
          onMouseOver={({target})=>target.style.backgroundColor='#48632F'} 
          onMouseOut={({target})=>target.style.backgroundColor='#5C832F'}
        >
          Shop Now
        </button>
      </div>

      <section className= "container my-5 p-5 bg-light rounded shadow-sm" style={{ margin: '50px auto', maxWidth: '1200px', textAlign: 'center', border: '1px solid black',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)', padding: '20px', borderRadius: '10px'}}>
        <h2 className = "mb-4" style={{ fontSize: '2.5rem', color: '#5C832F', marginBottom: '1rem', fontFamily: 'Roboto, sans-serif'  }}>About SOIL</h2>
        <hr />
        <p style={{ fontSize: '1.2rem', textAlign: 'justify', margin: '0 auto', maxWidth: '1000px', fontFamily: '"Open Sans", sans-serif' }}>
        SOIL is a long-term organic food grocer with several store locations around Melbourne, Australia.
         We focus on bringing premium, organic fresh food to the community. In addition to being food grocers, we also offer face-to-face
        seminars on diet, nutrition, and small-scale organic farming. In other words, we are a lot more than just an online shop.
        SOIL stands at the forefront of Melbourne's movement towards sustainable living and organic eating. Founded on the principles 
        of ecological balance and respect for the soil, we've been your local source of organic produce for over a decade.
        <br />
        <br />
        {/*The following snippets have been generated by OpenAI's ChatGPT up to the the last paragraph in this section
          Each section was written in own words following generation.
          OpenAI (2024) ChatGPT [Large language model], accessed 14 March 2024. (*Link could not be generated successfully*) */}
         At SOIL, we think that the first step towards a better life and world is choosing ethical food choices. We endeavour to uplift and 
        educate our community through our shops and workshops, promoting a food system that supports regional farmers, protects the environment, 
        and brings the freshest, tastiest produce straight to your table. Our consistent commitment to transparency, excellence, and community 
        engagement continues as we confront the challenges of a changing world. Come along as we, one meal at a time, cultivate a green future.
        </p>
        <br />
        <p style={{ fontSize: '1.2rem', textAlign: 'justify', margin: '0 auto', maxWidth: '1000px', fontFamily: '"Open Sans", sans-serif' }}>
        In addition to our retail business, SOIL is committed to supporting urban agriculture. We provide families and individuals the tools they
         need to grow their own food, lowering their carbon footprint and fostering a stronger connection with the environment through programmes 
         like our urban garden programme. Our dream is a world beyond the confines of traditional agriculture, where every home has access to 
         reasonably priced, nutrient-dense, and organically cultivated food. Every seed sown and community workshop conducted by SOIL establishes 
         a stronger foundation for sustainability in the core of Melbourne.
        </p>
      </section>
  

      <section className="container my-5 p-5 bg-light rounded shadow-sm" style={{ margin: '50px auto', maxWidth: '1200px', textAlign: 'center',
      border: '1px solid black', boxShadow: '0 4px 8px rgba(0,0,0,0.1)', padding: '20px', borderRadius: '10px'}}>
        <h2 className="mb-4" style={{ textAlign: 'center', marginBottom: '30px', fontSize: '2.5rem', color: '#5C832F', fontFamily: 'Roboto, sans-serif' }}>Backyard Gardening Insights</h2>
        <hr />
        <p style={{ fontSize: '1.2rem', textAlign: 'justify', margin: '0 auto', maxWidth: '1000px', fontFamily: '"Open Sans", sans-serif' }}>
        Taking up backyard gardening is a great way to be environmentally conscious while also adding fresh, organic produce to your diet.
          Important insights have been gained from our study of sustainable gardening techniques. Companion planting, for instance, can enhance 
          soil health and naturally ward off pests, which lowers the need for chemical inputs. Additionally, adding pollinator-friendly flowers 
          and native plants helps increase biodiversity, assisting bees and other helpful insects that are essential to a healthy ecosystem.
        </p>
        <br />
        <p style={{ fontSize: '1.2rem', textAlign: 'justify', margin: '0 auto', maxWidth: '1000px', fontFamily: '"Open Sans", sans-serif' }}>
        Soil health is another essential component of successful backyard gardening. Our research emphasises how crucial organic composting 
        is for boosting the nutritional content of soil and encouraging healthy plant growth. Composting yard waste and kitchen scraps allows 
        gardeners to establish a closed-loop system that replicates natural ecological cycles. Furthermore, by using rainwater gathering techniques,
         you may lessen the effects of drought on your garden and guarantee that your plants will flourish in spite of difficult circumstances.
        </p>
        <br />
        <p style={{ fontSize: '1.2rem', textAlign: 'justify', margin: '0 auto', maxWidth: '1000px', fontFamily: '"Open Sans", sans-serif' }}>
        We urge everyone in our community to take up gardening with enthusiasm and knowledge. Sustainable gardening, whether you're growing 
        one tomato plant on a balcony or turning your backyard into a paradise of greenery, is a step in the right direction towards a healthier 
        Earth. With workshops, the best organic seeds and gardening materials, and information, SOIL is here to help and encourage you. 
        Together, let's develop.
        </p>
      </section>

      <section className="container my-5 p-5 bg-light rounded shadow-sm" style={{ padding: '50px 20px', margin: '50px auto', maxWidth: '1200px', 
        border: '1px solid black', boxShadow: '0 4px 8px rgba(0,0,0,0.1)', borderRadius: '10px'}}>
        <h2 className="mb-4" style={{ fontSize: '2.5rem', color: '#5C832F', textAlign: 'center', fontFamily: 'Roboto, sans-serif' }}>Nutritional Advice & Backyard Gardening</h2>
        <hr />
        <div className="row g-4 d-flex" style={{display: 'flex'}}>
          <div className="col-md-4 mb-3 d-flex" style={{display: 'flex', flexDirection: 'column'}}>
            <h3 className="mb-3" style={{ fontFamily: 'Roboto, sans-serif', fontSize: '1.8rem'}}>Healthy Eating Tips</h3>
            <div style={{ background: '#fff', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.15)', flexGrow: 1 }}>
              <ul style={{ listStyleType: 'circle', padding: '10px', textAlign: 'left', fontFamily: 'Open Sans, sans-serif', fontSize: '1.1rem', marginBottom: 0 }}>
                <li style={{ marginBottom: '15px' }}>Eat a variety of foods</li>
                <li style={{ marginBottom: '15px' }}>Include plenty of fruits and vegetables in your diet</li>
                <li style={{ marginBottom: '15px' }}>Limit processed foods and sugary drinks</li>
                <li style={{ marginBottom: '15px' }}>Drink plenty of water</li>
                <li>Balance your meals with protein, carbohydrates, and fats</li>
                {/* Photo by <a href="https://unsplash.com/@ferhadd?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Farhad Ibrahimzade</a> on 
                <a href="https://unsplash.com/photos/person-holding-silver-fork-and-knife-qgGc_1a6xGc?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>*/}
                <img src="/healthy_eating.jpg" alt="healthy_eating" style={{ width: '250px', height:'250px', borderRadius: '10px', marginTop: '15px' }} />
              </ul>
            </div>
          </div>
          <div className="col-md-4 mb-3 d-flex" style={{display: 'flex', flexDirection: 'column'}}>
            <h3 className="mb-3" style={{ fontFamily: 'Roboto, sans-serif', fontSize: '1.8rem'}}>Benefits of Organic Foods</h3>
            <div style={{ background: '#fff', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.15)', flexGrow: 1 }}>
              <ul style={{ listStyleType: 'circle', padding: '10px', textAlign: 'left', fontFamily: 'Open Sans, sans-serif', fontSize: '1.1rem', marginBottom: 0 }}>
                <li style={{ marginBottom: '15px' }}>Higher in nutrients</li>
                <li style={{ marginBottom: '15px' }}>Free from synthetic pesticides and chemicals</li>
                <li style={{ marginBottom: '15px' }}>Supports sustainable farming practices</li>
                <li style={{ marginBottom: '15px' }}>Better for the environment</li>
                <li>May have better taste</li>
                {/* Photo by <a href="https://unsplash.com/@markusspiske?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Markus Spiske</a> 
                on <a href="https://unsplash.com/photos/person-watering-plant-sFydXGrt5OA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>*/}
                <img src="/home_organic_foods.jpg" alt="organic_foods" style={{ width: '250px', height: '250px', borderRadius: '10px', marginTop: '40px' }} />
              </ul>
            </div>
          </div>
          <div className="col-md-4 mb-3 d-flex" style={{display: 'flex', flexDirection: 'column'}}>
            <h3 className="mb-3" style={{ fontFamily: 'Roboto, sans-serif', fontSize: '1.8rem'}}>Grow Your Greens</h3>
            <div style={{ background: '#fff', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.15)', flexGrow: 1 }}>
              <ul style={{ listStyleType: 'circle', padding: '10px', textAlign: 'left', fontFamily: 'Open Sans, sans-serif', fontSize: '1.1rem', marginBottom: 0 }}>
                    {/*The following tips and tricks snippet for gardening was generated by OpenAI's ChatGPT */}
                <li style={{ marginBottom: '15px' }}>Start with easy-to-grow veggies like tomatoes, lettuce, and cucumbers</li>
                <li style={{ marginBottom: '15px' }}>Choose a sunny spot in your yard and prepare your soil with organic compost</li>
                <li style={{ marginBottom: '15px' }}>Water regularly, but avoid overwatering to prevent root rot</li>
                <li>Harvest in the morning for peak flavor and nutrition</li>
                {/* Photo by <a href="https://unsplash.com/@jupp?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jonathan Kemper</a> 
                on <a href="https://unsplash.com/photos/person-holding-green-plant-on-black-pot-CbZh3kaPxrE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>*/}
                <img src="/gardening.jpg" alt="gardening" style={{ width: '250px', height: '250px', borderRadius: '10px', marginTop: '20px' }} />
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section className="container my-5">
        <Carousel indicators={true} interval={5000} className="carousel-container" style={{ padding: '20px 0' }}>
          {/* First Slide */}
          <Carousel.Item>
            <h2 className="mb-4" style={{textAlign: 'center', marginBottom: '30px', fontSize: '2.5rem', color: '#5C832F', fontFamily: 'Roboto, sans-serif' }}>Featured Specials</h2>
            <div className="d-flex justify-content-center">
              { specialItems.slice(0, 4).map(special => (
                <Card style={{ width: '18rem', margin: '0 10px',  height: '300px' }} key={special.productID}>
                  <Card.Img variant="top" src={special.img} style={{ height: '140px', objectFit: 'cover' }} />
                  <Card.Body>
                    <Card.Title style={{ color: '#5C832F', fontWeight: 'bold', fontFamily: 'Open Sans, sans-serif',  marginBottom: '10px'}}>{special.name}</Card.Title>
                    <Card.Text style={{fontSize: '1.3rem', color: '#007bff', fontWeight: 500, fontFamily: 'Open Sans, sans-serif'}}>${special.price}</Card.Text>
                    <Button variant="success" onClick={navigateToSpecials}>Shop Now</Button>
                  </Card.Body>
                </Card>
              ))}
            </div>
          </Carousel.Item>

          {/* Second Slide */}
          <Carousel.Item>
            <h2 className="mb-4" style={{textAlign: 'center', marginBottom: '30px', fontSize: '2.5rem', color: '#5C832F', fontFamily: 'Roboto, sans-serif' }}>Featured Specials</h2>
            <div className="d-flex justify-content-center">
              {specialItems.slice(2, 6).map(special => (
                <Card style={{ width: '18rem', margin: '0 10px',  height: '300px' }} key={special.productID}>
                  <Card.Img variant="top" src={special.img} style={{ height: '140px', objectFit: 'cover' }} />
                  <Card.Body>
                    <Card.Title style={{ color: '#5C832F', fontWeight: 'bold', fontFamily: 'Open Sans, sans-serif',  marginBottom: '10px'}}>{special.name}</Card.Title>
                    <Card.Text style={{fontSize: '1.3rem', color: '#007bff', fontWeight: 500, fontFamily: 'Open Sans, sans-serif'}}>${special.price}</Card.Text>
                    <Button variant="success" onClick={navigateToSpecials}>Shop Now</Button>
                  </Card.Body>
                </Card>
              ))}
            </div>
          </Carousel.Item>
        </Carousel>
      </section>
    </div>
  );
}

export default Home;
